repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/snakemake/snakefmt
    rev: 0.11.2
    hooks:
      - id: snakefmt
        args: ["-l", "100"]
        files: ^workflow/

# IMPORTANT: do not touch virtualenvs, caches, build outputs
exclude: |
  (?x)^(
    \.git/|
    \.venv/|
    \.snakemake/|
    build/|dist/|
    .*\.egg-info/|
    __pycache__/|
    spineprep\.egg-info/|
    .*site-packages/.*|
    site/
  )
