name: Bug Report
description: Report a bug or unexpected behavior in SpinePrep
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below.

  - type: input
    id: version
    attributes:
      label: SpinePrep Version
      description: Output of `spineprep version`
      placeholder: "0.1.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear description of what went wrong
      placeholder: "When I run spineprep doctor, it reports..."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the issue
      placeholder: |
        1. Install SpinePrep v0.1.0
        2. Run `spineprep doctor`
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Output of `spineprep doctor` if available
      placeholder: |
        OS: Ubuntu 22.04
        Python: 3.11.0
        SCT: 7.1
        PAM50: /home/user/sct/data/PAM50

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Any error messages, stack traces, or log excerpts
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration (if relevant)
      description: Your config.yaml (redact sensitive paths)
      render: yaml

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have checked existing issues for duplicates
          required: true
        - label: I have run `spineprep doctor` and included the output above
          required: false
        - label: I can reproduce this on the latest version
          required: false

