openneuro_ds005884_cospine_motor: datasets/openneuro_ds005884_cospine_motor
openneuro_ds005883_cospine_pain: datasets/openneuro_ds005883_cospine_pain
openneuro_ds004386_spinalcord_rest_testretest: datasets/openneuro_ds004386_spinalcord_rest_testretest
openneuro_ds004616_spinalcord_handgrasp_task: datasets/openneuro_ds004616_spinalcord_handgrasp_task
internal_balgrist_motor_11: /mnt/hdd2/P1_CoSpi/pilot_motor/spine/rawdata
internal_balgrist_painmotor_21: /mnt/hdd2/P1_CoSpi/main_painmotor/spine/rawdata