# Minimal defaults (expand later as needed)
bids_root: null
output_dir: "./out"
pipeline:
  motion:
    fd_threshold: 0.5
    dvars_threshold: 1.5
confounds:
  acompcor:
    n_components: 6
registration:
  target: "PAM50"
  sct:
    enable: true
qc:
  enable: true
