# SpinePrep default configuration
# CLI args and user YAML files override these defaults

bids_root: null
output_dir: "./out"

motion:
  fd:
    threshold: 0.5  # mm
  dvars:
    threshold: 1.5
  highpass:
    hz: 0.008  # Hz

confounds:
  acompcor:
    n_components: 6
  tcompcor:
    n_components: 0
  censor:
    method: "fd"  # One of: fd, dvars, fd+dvars

registration:
  pam50:
    spacing: "0.5mm"
  resample:
    to: "native"  # One of: native, pam50
  deformable:
    enabled: false

qc:
  ssim:
    min: 0.85
  psnr:
    min: 20.0
  report:
    embed_assets: true
