pipeline_version: "0.2.0"
project_name: "SpinePrep"

study:
  name: "MyFirstStudy"

paths:
  root: "/mnt/ssd1/MyFirstStudy"
  bids_dir: "{root}/bids"
  deriv_dir: "{root}/derivatives/spineprep"
  work_dir: "{root}/work/spineprep"
  logs_dir: "{deriv_dir}/logs"

dataset:
  sessions: null
  runs_per_subject: null

acq:
  tr: 1.2
  slice_timing: "ascending"
  pe_dir: "AP"
  echo_spacing_s: null

options:
  ingest:
    enable: false
  denoise_mppca: true
  motion:
    engine: "sct+rigid3d"
    slice_axis: "IS"
    concat:
      mode: "session+task"
      require_same: ["pe_dir", "slice_axis", "tr", "voxel_size"]
  smoothing:
    enable: false
    fwhm_mm: 2.0
  sdc:
    enable: true
    mode: "auto"
  temporal_crop:
    enable: true
    method: "cord_mean_robust_z"
    max_trim_start: 10
    max_trim_end: 10
    z_thresh: 2.5
  confounds:
    fd_method: "power_fd"
    dvars_method: "std_dvars"
  censor:
    enable: true
    fd_thresh_mm: 0.5
    dvars_thresh: 1.5
    min_contig_vols: 5
    pad_vols: 1
  masks:
    enable: true
    source: "sct"
    binarize_thr: 0.5
  acompcor:
    enable: true
    tissues: ["cord", "wm", "csf"]
    n_components_per_tissue: 5
    highpass_hz: 0.008
    detrend: true
    standardize: true
    explained_variance_min: 0.0
  first_level:
    engine: "feat"
    feat_variant: "block_15s_conv3"
  cleanup:
    keep_only_latest_stage: false

registration:
  enable: true
  template: PAM50
  guidance: SCT
  levels: auto
  use_gm_wm_masks: true
  rootlets:
    enable: false
    mode: "atlas"

templates:
  pam50_version: "1.0"

tools:
  sct: "7.1.0"
  sct_min_version: "5.8"
  fsl: "6.0.7"
  ants: "2.5.3"
  dcm2niix: "v1.0.2024"

resources:
  default_threads: 32
  default_mem_gb: 128

qc:
  subject_report: true
  cohort_report: false

runtime:
  container_engine: null
