<<<<<<< HEAD
name: docs

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
=======
name: Documentation CI

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'scripts/**'
      - 'mkdocs.yml'
      - 'schemas/**'
      - 'workflow/lib/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'scripts/**'
      - 'mkdocs.yml'
      - 'schemas/**'
      - 'workflow/lib/**'
>>>>>>> dadbaa4 (feat(docs): stand up MkDocs Material site with generators  [spi-011])

jobs:
  build:
    runs-on: ubuntu-latest
<<<<<<< HEAD
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdocs-sitemap-plugin

      # If you have generators with --check, add them here (optional):
      # - name: Check generated refs
      #   run: |
      #     python scripts/gen_docs_config_ref.py --check
      #     python scripts/gen_docs_api_ref.py --check

      - name: Build site
        run: mkdocs build --strict

      - name: Upload built site as artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site

  deploy_org_root:
    name: Deploy to spineprep.github.io
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download built site
        uses: actions/download-artifact@v4
        with:
          name: site
          path: site

      - name: Publish to spineprep/spineprep.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAGES_DEPLOY_TOKEN }}
          external_repository: spineprep/spineprep.github.io
          publish_branch: main
          publish_dir: ./site
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_message: "Deploy site from SpinePrep@${{ github.sha }}"
=======

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs-material
        pip install mkdocs-minify
        pip install mkdocs-redirects
        pip install mkdocs-table-reader
        pip install mkdocs-git-committers
        pip install mkdocs-rss-plugin
        pip install mkdocs-section-index
        pip install pymdown-extensions
        pip install ruff
        pip install codespell
        pip install lychee
        pip install snakefmt

    - name: Generate configuration reference
      run: |
        python scripts/gen_docs_config_ref.py --check

    - name: Generate API reference
      run: |
        python scripts/gen_docs_api_ref.py --check

    - name: Lint Python code
      run: |
        ruff check . && ruff format --check .

    - name: Lint Snakefile
      run: |
        snakefmt -l 100 workflow --check

    - name: Spell check
      run: |
        codespell --ignore-words-list="te,hist,nd" docs/

    - name: Check links
      run: |
        lychee --no-progress --exclude-mail --accept 200,206,429 "docs/**/*.md"

    - name: Build documentation
      run: |
        mkdocs build --strict

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        cname: spineprep.readthedocs.io
>>>>>>> dadbaa4 (feat(docs): stand up MkDocs Material site with generators  [spi-011])
