name: Documentation CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    name: Build and Validate Docs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Ensure built site is not tracked
        run: |
          if git ls-files --error-unmatch site 2>/dev/null; then
            echo "ERROR: 'site/' is tracked by git. Remove it with 'git rm -r --cached site' and commit."
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "mkdocs>=1.5,<2.0" "mkdocs-material>=9.5,<10.0"
          pip install ruff codespell snakefmt

      - name: Lint (ruff)
        run: |
          ruff check . && ruff format --check .

      - name: Snakefmt diff (diagnostics)
        run: |
          set +e
          snakefmt -l 100 workflow --diff
          exit 0

      - name: Lint Snakefiles
        run: |
          snakefmt -l 100 workflow --check

      - name: Spell check
        run: |
          codespell docs/ mkdocs.yml

      - name: Guard forbid public PLAYBOOK pages
        run: |
          if git ls-files --error-unmatch "docs/PLAYBOOK_*.md" >/dev/null 2>&1; then
            echo "ERROR: docs/PLAYBOOK_*.md must not be committed."
            exit 1
          fi

      - name: Generate references --check
        run: |
          python scripts/gen_docs_config_ref.py --check
          python scripts/gen_docs_api_ref.py --check

      - name: Link check
        uses: lycheeverse/lychee-action@v2
        with:
          args: >
            --config lychee.toml
            docs/**/*.md

      - name: Build site
        run: |
          mkdocs build --strict

      - name: Verify site output and list contents (diagnostics)
        run: |
          pwd
          ls -la
          if [ ! -d site ]; then
            echo "ERROR: site/ directory not found after mkdocs build"
            exit 1
          fi
          ls -la site

      - name: Upload site as artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: ./site

      - name: Upload screenshots
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: docs/_assets/screenshots/*.png

  deploy:
    name: Deploy to spineprep.github.io
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download site from docs job
        uses: actions/download-artifact@v4
        with:
          name: site
          path: ./site
      - name: Deploy to spineprep.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAGES_DEPLOY_TOKEN }}
          external_repository: spineprep/spineprep.github.io
          publish_branch: main
          publish_dir: ./site
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_message: "Deploy site from SpinePrep@${{ github.sha }}"
      - name: Announce live URL
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "Live site: https://spineprep.github.io" >> $GITHUB_STEP_SUMMARY

  release:
    name: Publish versioned docs (mike)
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install mike
        run: |
          python -m pip install --upgrade pip
          pip install mike "mkdocs>=1.5,<2.0" "mkdocs-material>=9.5,<10.0"
      - name: Configure git identity
        run: |
          git config user.email "${{ secrets.GIT_USER_EMAIL || '41898282+github-actions[bot]@users.noreply.github.com' }}"
          git config user.name  "${{ secrets.GIT_USER_NAME  || 'github-actions[bot]' }}"
      - name: Set VERSION env
        run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
      - name: Add Pages repo remote
        env:
          GH_PAT: ${{ secrets.PAGES_DEPLOY_TOKEN }}
        run: |
          git remote add pages https://x-access-token:${GH_PAT}@github.com/spineprep/spineprep.github.io.git
          git fetch pages
          git branch -r
      - name: Release with mike
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          bash scripts/docs_release.sh
      - name: Announce versioned URLs
        run: |
          echo "Latest: https://spineprep.github.io/" >> $GITHUB_STEP_SUMMARY
          echo "Stable: https://spineprep.github.io/stable/" >> $GITHUB_STEP_SUMMARY
